server:
  port: 8081
properties:
  timeout: "10000"


springbootwebfluxjjwt:
  password:
    encoder:
      secret: "asdjbyirtgkmlktrerbtind"
      iteration: 33
      keylength: 256
  jjwt:
    secret: "ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength"
    expiration: 28800


application:
  error:
    message:
      invalid-credentials: "Credenciales invalidas."
      not-found-user: "No existe usuario"
  resources:
    user-management:
      services:
        uri: "http://user-management:8080/api/v1/user"
        #uri: "http://localhost:8080/api/v1/user"
